import os

import requests
import streamlit as st

MIDDLEWARE_URL = os.getenv("MIDDLEWARE_URL", "http://127.0.0.1:5000")

SUGGESTED_QUESTIONS = [
    "Summarize the latest indoor conditions.",
    "Summarize yesterday.",
    "What was the average temperature over the last 24 hours?",
    "How many times was motion detected?",
    "Was humidity too low recently?",
    "How was the air quality over the last day?",
    "Should I ventilate the room?",
]


def _ask(question: str, device_id: str, hours: int):
    response = requests.post(
        f"{MIDDLEWARE_URL}/api/voice/ask",
        json={"question": question, "device_id": device_id or None, "hours": hours},
        timeout=30,
    )
    response.raise_for_status()
    return response.json()


def _tts(text: str):
    response = requests.post(
        f"{MIDDLEWARE_URL}/api/voice/tts",
        json={"text": text},
        timeout=45,
    )
    if response.status_code >= 400:
        try:
            detail = response.json().get("error", response.text)
        except ValueError:
            detail = response.text
        raise requests.HTTPError(detail or f"TTS failed with status {response.status_code}")
    return (
        response.content,
        response.headers.get("X-TTS-Provider", "tts"),
        response.headers.get("Content-Type", "audio/mpeg").split(";")[0],
    )


def render():
    st.title("Ask Data")
    st.caption("Ask Gemini about indoor readings, outdoor weather, and historical trends.")

    col1, col2 = st.columns([2, 1])
    with col1:
        device_id = st.text_input("Device ID filter", value="", placeholder="All devices")
    with col2:
        hours = st.selectbox("Time window", [1, 2, 6, 12, 24, 48, 168], index=4)

    if "ask_question" not in st.session_state:
        st.session_state["ask_question"] = SUGGESTED_QUESTIONS[0]

    with st.expander("Suggested questions", expanded=True):
        cols = st.columns(2)
        for index, suggested in enumerate(SUGGESTED_QUESTIONS):
            with cols[index % 2]:
                if st.button(suggested, use_container_width=True):
                    st.session_state["ask_question"] = suggested

    question = st.text_area(
        "Question",
        key="ask_question",
        height=100,
        placeholder="Ask something like: What was the average humidity today?",
    )

    ask_col, clear_col = st.columns([3, 1])
    with ask_col:
        ask_clicked = st.button("Ask", type="primary", use_container_width=True)
    with clear_col:
        if st.button("Clear", use_container_width=True):
            st.session_state.pop("last_answer_result", None)
            st.session_state.pop("last_answer_audio", None)
            st.rerun()

    if ask_clicked:
        if not question.strip():
            st.warning("Write a question first.")
        else:
            with st.spinner("Analyzing BigQuery data..."):
                try:
                    result = _ask(question=question, device_id=device_id, hours=hours)
                except requests.RequestException as exc:
                    st.error(f"Could not reach the assistant API: {exc}")
                    return
            st.session_state["last_answer_result"] = result
            st.session_state.pop("last_answer_audio", None)
            st.session_state.pop("last_answer_audio_provider", None)

    result = st.session_state.get("last_answer_result")
    if result:
        st.markdown("### Answer")
        answer = result.get("answer", "No answer returned.")
        st.markdown(f"""
        <div style="
            background:#111827;
            border:1px solid #334155;
            border-radius:8px;
            padding:1rem 1.1rem;
            color:#e5e7eb;
            line-height:1.55;
        ">{answer}</div>
        """, unsafe_allow_html=True)

        source = result.get("source", "unknown")
        if source == "local-fallback":
            st.info("Answer generated with local analytics because OPENAI_API_KEY is not configured.")
        elif source == "local-fallback-after-error":
            st.warning("The AI call failed, so the dashboard used local analytics instead.")
        else:
            st.caption(f"Answer generated by {source}.")

        speak_col, _ = st.columns([1.2, 2.8])
        with speak_col:
            if st.button("Speak answer", use_container_width=True):
                with st.spinner("Generating speech..."):
                    try:
                        audio, provider, content_type = _tts(answer)
                    except requests.RequestException as exc:
                        st.error(f"Could not generate speech: {exc}")
                    else:
                        st.session_state["last_answer_audio"] = audio
                        st.session_state["last_answer_audio_provider"] = provider
                        st.session_state["last_answer_audio_type"] = content_type

        audio = st.session_state.get("last_answer_audio")
        if audio:
            st.audio(audio, format=st.session_state.get("last_answer_audio_type", "audio/mpeg"))
            st.caption(f"Audio generated by {st.session_state.get('last_answer_audio_provider', 'tts')}.")

        with st.expander("Data used for answer", expanded=False):
            st.json(result.get("context", {}))
