-- Schema des tables BigQuery (Mis à jour pour le schéma personnalisé).
--
-- Table indoor_sensor_data :
--   timestamp (TIMESTAMP, REQUIRED)
--   device_id (STRING, REQUIRED)
--   temperature_c (FLOAT, NULLABLE)
--   humidity_percent (FLOAT, NULLABLE)
--   co2_ppm (INTEGER, NULLABLE)
--   tvoc_ppb (INTEGER, NULLABLE)
--   motion_detected (BOOLEAN, NULLABLE)
--
-- Table outdoor_weather_data :
--   timestamp (TIMESTAMP, REQUIRED)
--   location_name (STRING, REQUIRED)
--   outdoor_temp_c (FLOAT, NULLABLE)
--   humidity_percent (FLOAT, NULLABLE)
--   weather_condition (STRING, NULLABLE)
--   weather_icon (STRING, NULLABLE)
